### ISSUE TITLE
Algorithm identifiers like HPKE-P256-SHA256-A128GCM are overly verbose

### ISSUE THREAD

**Issue by selfissued** [ietf-wg-jose/draft-ietf-jose-hpke-encrypt#8]
The "alg" values should be short identifiers that fully-specify the computation to be performed. They should not contain syntax that is parsed, such as a required "HPKE" string prefix.

Let's decide on reasonable short identifiers for each of the algorithms - ideally 8 characters each or less.

**Comment by OR13** [comment]
Hpke Jose Cipher Suite 0 - HPKE-P256-SHA256-A128GCM -> HJCS-0 ?

**Comment by OR13** [comment]
`ECDH-ES+A128KW` has obvious structure.

https://www.iana.org/assignments/hpke/hpke.xhtml has the source of truth for the values.

**Comment by selfissued** [comment]
In order to have meaningful short algorithm names, I propose that we use `alg` names of the form "HPKEk-a", where "n" is the hexadecimal representation of the HPKE KEM number and "a" is the hexadecimal representation of the HPKE AEAD number, both as registered at https://www.iana.org/assignments/hpke/hpke.xhtml.  In particular, I'm proposing these renamings:

- `HPKE-P256-SHA256-A128GCM` -> `HPKE10-1`
- `HPKE-P384-SHA384-A256GCM` -> `HPKE11-2`
- `HPKE-P521-SHA512-A256GCM` -> `HPKE12-2`
- `HPKE-X25519-SHA256-A128GCM` -> `HPKE20-1`
- `HPKE-X25519-SHA256-ChaCha20Poly1305` -> `HPKE20-3`
- `HPKE-X448-SHA512-A256GCM` -> `HPKE21-2`
- `HPKE-X448-SHA512-ChaCha20Poly1305` -> `HPKE21-2`

I will create a PR unless people make a counterproposal.

**Comment by OR13** [comment]
If we are going to go for shorter names, I think we can skip straight to `HPKE-[0-N]`

**Comment by selfissued** [comment]
The two numbers are aligned to the numbers in the registries at https://www.iana.org/assignments/hpke/hpke.xhtml.  Then were not making anything up.

I could live with either approach.  What do others think?

**Comment by OR13** [comment]
ahh, maybe just `hpke-<kem>-<kdf>-<aead>` but using numbers instead of string labels

**Comment by OR13** [comment]
Still seems like it might be better to just go with `hpke-0` though... shorter, and the registration can handle the mapping

**Comment by selfissued** [comment]
I could support hpke-kem-kdf-aead naming like `HPKE-10-1-1` (leaving off the leading zeros).  I'd rather go with names rooted in the existing HPKE registry than names we're completely making up.

**Comment by ilaril** [comment]
One subtle consideration is that any sort of systematic pattern can be interpreted as adding all the algorithms (since it is obvious what the algorithm name would be). Advantage of being systematic would be eliminating the possibility that an algorithm gets added in subtly incompatible way (which could cause major interoperability headaches).

Then these algorithms could presumably get used with kty=AKP. There is an obvious interpretation for "priv" and "pub" in this case (raw HPKE private and public keys).

However, it depends on KEM if it is possible to derive "pub" from "priv" (and including both causes possible security issue), or not (both are needed). I think KEM 0x30 (which is essentially deprecated) is currently the only one where it is not possible to derive public key from private key.

**Comment by ounsworth** [comment]
My vote (that doesn't count because I'm a tourist in JOSE):

Fully specified is useful so that devs don't need to fish around in the guts of RFCs to figure out what actually makes up a given cipher suite.

Short-forms over the wire are also fine. I have a slight preference for `HPKE-0` rather than `HPKE10-1` because A) if you have to look it up, then you have to look it up, and B) this scheme may not extend well to hybrid KEMs.

**Comment by OR13** [comment]
Its also easier to read, write and compare "HPKE-0" in contrast to "HPKE-P256-SHA265-A128GCM" (review this carefully for a case in point).
